version: '3.8'
services:
  database:
    image: 'postgres:16.0-alpine3.18'
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
